export const CREATE_ODER_REQUEST = "CREATE_ODER_REQUEST";
export const CREATE_ODER_SUCCESS = "CREATE_ODER_FAILED";
export const CREATE_ODER_FAILED = "CREATE_ODER_FAILED";

export const ODER_REQUEST = "ODER_REQUEST";
export const ODER_SUCCESS = "ODER_FAILED";
export const ODER_FAILED = "ODER_FAILED";

export const DELETE_ODER = "DELETE_ODER";
