export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SHIPPING_ADDRESS_SUCCESSE = "SHIPPING_ADDRESS_SUCCESSE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";